-- AlterTable
ALTER TABLE `alerts` MODIFY COLUMN `tipo` ENUM('RECORDATORIO_CITA', 'SOBRECARGA_AGENDA', 'INASISTENCIA_FRECUENTE', 'LISTA_ESPERA_LARGA', 'SLOT_LIBRE_DISPONIBLE', 'CITA_CANCELADA', 'CITA_NO_ASISTIO') NOT NULL;
